//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBX_Web_PetShopWeb.wsSistema {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session_Movi", Namespace="http://schemas.datacontract.org/2004/07/Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Session_Movi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dttFeRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdEntidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdSesionMovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdSoftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strIpHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNomEntidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tinNuOperaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dttFeRegistro {
            get {
                return this.dttFeRegistroField;
            }
            set {
                if ((this.dttFeRegistroField.Equals(value) != true)) {
                    this.dttFeRegistroField = value;
                    this.RaisePropertyChanged("dttFeRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdEntid {
            get {
                return this.intIdEntidField;
            }
            set {
                if ((this.intIdEntidField.Equals(value) != true)) {
                    this.intIdEntidField = value;
                    this.RaisePropertyChanged("intIdEntid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdMenu {
            get {
                return this.intIdMenuField;
            }
            set {
                if ((this.intIdMenuField.Equals(value) != true)) {
                    this.intIdMenuField = value;
                    this.RaisePropertyChanged("intIdMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdSesion {
            get {
                return this.intIdSesionField;
            }
            set {
                if ((this.intIdSesionField.Equals(value) != true)) {
                    this.intIdSesionField = value;
                    this.RaisePropertyChanged("intIdSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdSesionMov {
            get {
                return this.intIdSesionMovField;
            }
            set {
                if ((this.intIdSesionMovField.Equals(value) != true)) {
                    this.intIdSesionMovField = value;
                    this.RaisePropertyChanged("intIdSesionMov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdSoft {
            get {
                return this.intIdSoftField;
            }
            set {
                if ((this.intIdSoftField.Equals(value) != true)) {
                    this.intIdSoftField = value;
                    this.RaisePropertyChanged("intIdSoft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdUsuario {
            get {
                return this.intIdUsuarioField;
            }
            set {
                if ((this.intIdUsuarioField.Equals(value) != true)) {
                    this.intIdUsuarioField = value;
                    this.RaisePropertyChanged("intIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdentity {
            get {
                return this.intIdentityField;
            }
            set {
                if ((this.intIdentityField.Equals(value) != true)) {
                    this.intIdentityField = value;
                    this.RaisePropertyChanged("intIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strIpHost {
            get {
                return this.strIpHostField;
            }
            set {
                if ((object.ReferenceEquals(this.strIpHostField, value) != true)) {
                    this.strIpHostField = value;
                    this.RaisePropertyChanged("strIpHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNomEntid {
            get {
                return this.strNomEntidField;
            }
            set {
                if ((object.ReferenceEquals(this.strNomEntidField, value) != true)) {
                    this.strNomEntidField = value;
                    this.RaisePropertyChanged("strNomEntid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tinNuOpera {
            get {
                return this.tinNuOperaField;
            }
            set {
                if ((this.tinNuOperaField.Equals(value) != true)) {
                    this.tinNuOperaField = value;
                    this.RaisePropertyChanged("tinNuOpera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consumo", Namespace="http://schemas.datacontract.org/2004/07/Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Consumo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlCanceladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitFlCanceladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bitFlConsumidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitFlEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitMarcaDNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitTodosTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFeHoraAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFeHoraDeshaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFeModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFeRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttFechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dttHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCantMaxConsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdAsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdConsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdReglaNegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdTipServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdUsuarModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdUsuarRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intTipoPeriodoConsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal monCostoServField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDesEmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDesMarcadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDesTipMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDesTipServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFotocheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strHorarioAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombresCompletosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNumDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTipoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarDeshaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantC {
            get {
                return this.CantCField;
            }
            set {
                if ((this.CantCField.Equals(value) != true)) {
                    this.CantCField = value;
                    this.RaisePropertyChanged("CantC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantS {
            get {
                return this.CantSField;
            }
            set {
                if ((this.CantSField.Equals(value) != true)) {
                    this.CantSField = value;
                    this.RaisePropertyChanged("CantS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlCancelado {
            get {
                return this.FlCanceladoField;
            }
            set {
                if ((this.FlCanceladoField.Equals(value) != true)) {
                    this.FlCanceladoField = value;
                    this.RaisePropertyChanged("FlCancelado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sim {
            get {
                return this.SimField;
            }
            set {
                if ((object.ReferenceEquals(this.SimField, value) != true)) {
                    this.SimField = value;
                    this.RaisePropertyChanged("Sim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalC {
            get {
                return this.TotalCField;
            }
            set {
                if ((this.TotalCField.Equals(value) != true)) {
                    this.TotalCField = value;
                    this.RaisePropertyChanged("TotalC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalS {
            get {
                return this.TotalSField;
            }
            set {
                if ((this.TotalSField.Equals(value) != true)) {
                    this.TotalSField = value;
                    this.RaisePropertyChanged("TotalS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitFlCancelado {
            get {
                return this.bitFlCanceladoField;
            }
            set {
                if ((this.bitFlCanceladoField.Equals(value) != true)) {
                    this.bitFlCanceladoField = value;
                    this.RaisePropertyChanged("bitFlCancelado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bitFlConsumido {
            get {
                return this.bitFlConsumidoField;
            }
            set {
                if ((this.bitFlConsumidoField.Equals(value) != true)) {
                    this.bitFlConsumidoField = value;
                    this.RaisePropertyChanged("bitFlConsumido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitFlEliminado {
            get {
                return this.bitFlEliminadoField;
            }
            set {
                if ((this.bitFlEliminadoField.Equals(value) != true)) {
                    this.bitFlEliminadoField = value;
                    this.RaisePropertyChanged("bitFlEliminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitMarcaDNI {
            get {
                return this.bitMarcaDNIField;
            }
            set {
                if ((this.bitMarcaDNIField.Equals(value) != true)) {
                    this.bitMarcaDNIField = value;
                    this.RaisePropertyChanged("bitMarcaDNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitTodosTS {
            get {
                return this.bitTodosTSField;
            }
            set {
                if ((this.bitTodosTSField.Equals(value) != true)) {
                    this.bitTodosTSField = value;
                    this.RaisePropertyChanged("bitTodosTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFeHoraAutor {
            get {
                return this.dttFeHoraAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFeHoraAutorField, value) != true)) {
                    this.dttFeHoraAutorField = value;
                    this.RaisePropertyChanged("dttFeHoraAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFeHoraDesha {
            get {
                return this.dttFeHoraDeshaField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFeHoraDeshaField, value) != true)) {
                    this.dttFeHoraDeshaField = value;
                    this.RaisePropertyChanged("dttFeHoraDesha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFeModif {
            get {
                return this.dttFeModifField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFeModifField, value) != true)) {
                    this.dttFeModifField = value;
                    this.RaisePropertyChanged("dttFeModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFeRegistro {
            get {
                return this.dttFeRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFeRegistroField, value) != true)) {
                    this.dttFeRegistroField = value;
                    this.RaisePropertyChanged("dttFeRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFecha {
            get {
                return this.dttFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFechaField, value) != true)) {
                    this.dttFechaField = value;
                    this.RaisePropertyChanged("dttFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttFechaHora {
            get {
                return this.dttFechaHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.dttFechaHoraField, value) != true)) {
                    this.dttFechaHoraField = value;
                    this.RaisePropertyChanged("dttFechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dttHora {
            get {
                return this.dttHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.dttHoraField, value) != true)) {
                    this.dttHoraField = value;
                    this.RaisePropertyChanged("dttHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgFoto {
            get {
                return this.imgFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.imgFotoField, value) != true)) {
                    this.imgFotoField = value;
                    this.RaisePropertyChanged("imgFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCantMaxConsumo {
            get {
                return this.intCantMaxConsumoField;
            }
            set {
                if ((this.intCantMaxConsumoField.Equals(value) != true)) {
                    this.intCantMaxConsumoField = value;
                    this.RaisePropertyChanged("intCantMaxConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCantidad {
            get {
                return this.intCantidadField;
            }
            set {
                if ((this.intCantidadField.Equals(value) != true)) {
                    this.intCantidadField = value;
                    this.RaisePropertyChanged("intCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdAsistencia {
            get {
                return this.intIdAsistenciaField;
            }
            set {
                if ((this.intIdAsistenciaField.Equals(value) != true)) {
                    this.intIdAsistenciaField = value;
                    this.RaisePropertyChanged("intIdAsistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdConsumo {
            get {
                return this.intIdConsumoField;
            }
            set {
                if ((this.intIdConsumoField.Equals(value) != true)) {
                    this.intIdConsumoField = value;
                    this.RaisePropertyChanged("intIdConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdPersonal {
            get {
                return this.intIdPersonalField;
            }
            set {
                if ((this.intIdPersonalField.Equals(value) != true)) {
                    this.intIdPersonalField = value;
                    this.RaisePropertyChanged("intIdPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdReglaNeg {
            get {
                return this.intIdReglaNegField;
            }
            set {
                if ((this.intIdReglaNegField.Equals(value) != true)) {
                    this.intIdReglaNegField = value;
                    this.RaisePropertyChanged("intIdReglaNeg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdServicio {
            get {
                return this.intIdServicioField;
            }
            set {
                if ((this.intIdServicioField.Equals(value) != true)) {
                    this.intIdServicioField = value;
                    this.RaisePropertyChanged("intIdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdTipServ {
            get {
                return this.intIdTipServField;
            }
            set {
                if ((this.intIdTipServField.Equals(value) != true)) {
                    this.intIdTipServField = value;
                    this.RaisePropertyChanged("intIdTipServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdUsuarModif {
            get {
                return this.intIdUsuarModifField;
            }
            set {
                if ((this.intIdUsuarModifField.Equals(value) != true)) {
                    this.intIdUsuarModifField = value;
                    this.RaisePropertyChanged("intIdUsuarModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdUsuarReg {
            get {
                return this.intIdUsuarRegField;
            }
            set {
                if ((this.intIdUsuarRegField.Equals(value) != true)) {
                    this.intIdUsuarRegField = value;
                    this.RaisePropertyChanged("intIdUsuarReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intTipoPeriodoConsumo {
            get {
                return this.intTipoPeriodoConsumoField;
            }
            set {
                if ((this.intTipoPeriodoConsumoField.Equals(value) != true)) {
                    this.intTipoPeriodoConsumoField = value;
                    this.RaisePropertyChanged("intTipoPeriodoConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal monCostoServ {
            get {
                return this.monCostoServField;
            }
            set {
                if ((this.monCostoServField.Equals(value) != true)) {
                    this.monCostoServField = value;
                    this.RaisePropertyChanged("monCostoServ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strApePaterno {
            get {
                return this.strApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.strApePaternoField, value) != true)) {
                    this.strApePaternoField = value;
                    this.RaisePropertyChanged("strApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCantidad {
            get {
                return this.strCantidadField;
            }
            set {
                if ((object.ReferenceEquals(this.strCantidadField, value) != true)) {
                    this.strCantidadField = value;
                    this.RaisePropertyChanged("strCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strClase {
            get {
                return this.strClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.strClaseField, value) != true)) {
                    this.strClaseField = value;
                    this.RaisePropertyChanged("strClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDesEmp {
            get {
                return this.strDesEmpField;
            }
            set {
                if ((object.ReferenceEquals(this.strDesEmpField, value) != true)) {
                    this.strDesEmpField = value;
                    this.RaisePropertyChanged("strDesEmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDesMarcador {
            get {
                return this.strDesMarcadorField;
            }
            set {
                if ((object.ReferenceEquals(this.strDesMarcadorField, value) != true)) {
                    this.strDesMarcadorField = value;
                    this.RaisePropertyChanged("strDesMarcador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDesTipMenu {
            get {
                return this.strDesTipMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.strDesTipMenuField, value) != true)) {
                    this.strDesTipMenuField = value;
                    this.RaisePropertyChanged("strDesTipMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDesTipServicio {
            get {
                return this.strDesTipServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.strDesTipServicioField, value) != true)) {
                    this.strDesTipServicioField = value;
                    this.RaisePropertyChanged("strDesTipServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDescripcion {
            get {
                return this.strDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDescripcionField, value) != true)) {
                    this.strDescripcionField = value;
                    this.RaisePropertyChanged("strDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFotocheck {
            get {
                return this.strFotocheckField;
            }
            set {
                if ((object.ReferenceEquals(this.strFotocheckField, value) != true)) {
                    this.strFotocheckField = value;
                    this.RaisePropertyChanged("strFotocheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strHorarioAtencion {
            get {
                return this.strHorarioAtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.strHorarioAtencionField, value) != true)) {
                    this.strHorarioAtencionField = value;
                    this.RaisePropertyChanged("strHorarioAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombres {
            get {
                return this.strNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombresField, value) != true)) {
                    this.strNombresField = value;
                    this.RaisePropertyChanged("strNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombresCompletos {
            get {
                return this.strNombresCompletosField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombresCompletosField, value) != true)) {
                    this.strNombresCompletosField = value;
                    this.RaisePropertyChanged("strNombresCompletos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNumDoc {
            get {
                return this.strNumDocField;
            }
            set {
                if ((object.ReferenceEquals(this.strNumDocField, value) != true)) {
                    this.strNumDocField = value;
                    this.RaisePropertyChanged("strNumDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strObservacion {
            get {
                return this.strObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.strObservacionField, value) != true)) {
                    this.strObservacionField = value;
                    this.RaisePropertyChanged("strObservacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPrecio {
            get {
                return this.strPrecioField;
            }
            set {
                if ((object.ReferenceEquals(this.strPrecioField, value) != true)) {
                    this.strPrecioField = value;
                    this.RaisePropertyChanged("strPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTipoServicio {
            get {
                return this.strTipoServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.strTipoServicioField, value) != true)) {
                    this.strTipoServicioField = value;
                    this.RaisePropertyChanged("strTipoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuarAutor {
            get {
                return this.strUsuarAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarAutorField, value) != true)) {
                    this.strUsuarAutorField = value;
                    this.RaisePropertyChanged("strUsuarAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuarDesha {
            get {
                return this.strUsuarDeshaField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarDeshaField, value) != true)) {
                    this.strUsuarDeshaField = value;
                    this.RaisePropertyChanged("strUsuarDesha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSConfi", Namespace="http://schemas.datacontract.org/2004/07/Dominio.Entidades.Sistema")]
    [System.SerializableAttribute()]
    public partial class TSConfi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitFlActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dttFeRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdConfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdSoftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCoConfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDesConfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPosibValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strValorConfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoControlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitFlActivo {
            get {
                return this.bitFlActivoField;
            }
            set {
                if ((this.bitFlActivoField.Equals(value) != true)) {
                    this.bitFlActivoField = value;
                    this.RaisePropertyChanged("bitFlActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dttFeRegistro {
            get {
                return this.dttFeRegistroField;
            }
            set {
                if ((this.dttFeRegistroField.Equals(value) != true)) {
                    this.dttFeRegistroField = value;
                    this.RaisePropertyChanged("dttFeRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdConfi {
            get {
                return this.intIdConfiField;
            }
            set {
                if ((this.intIdConfiField.Equals(value) != true)) {
                    this.intIdConfiField = value;
                    this.RaisePropertyChanged("intIdConfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdSoft {
            get {
                return this.intIdSoftField;
            }
            set {
                if ((this.intIdSoftField.Equals(value) != true)) {
                    this.intIdSoftField = value;
                    this.RaisePropertyChanged("intIdSoft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCoConfi {
            get {
                return this.strCoConfiField;
            }
            set {
                if ((object.ReferenceEquals(this.strCoConfiField, value) != true)) {
                    this.strCoConfiField = value;
                    this.RaisePropertyChanged("strCoConfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDesConfi {
            get {
                return this.strDesConfiField;
            }
            set {
                if ((object.ReferenceEquals(this.strDesConfiField, value) != true)) {
                    this.strDesConfiField = value;
                    this.RaisePropertyChanged("strDesConfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPosibValor {
            get {
                return this.strPosibValorField;
            }
            set {
                if ((object.ReferenceEquals(this.strPosibValorField, value) != true)) {
                    this.strPosibValorField = value;
                    this.RaisePropertyChanged("strPosibValor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strValorConfi {
            get {
                return this.strValorConfiField;
            }
            set {
                if ((object.ReferenceEquals(this.strValorConfiField, value) != true)) {
                    this.strValorConfiField = value;
                    this.RaisePropertyChanged("strValorConfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoControl {
            get {
                return this.tipoControlField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoControlField, value) != true)) {
                    this.tipoControlField = value;
                    this.RaisePropertyChanged("tipoControl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSistema.ISistemaSrv")]
    public interface ISistemaSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaSrv/ImpresionTicket", ReplyAction="http://tempuri.org/ISistemaSrv/ImpresionTicketResponse")]
        CBX_Web_PetShopWeb.wsSistema.ImpresionTicketResponse ImpresionTicket(CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaSrv/ImpresionTicket", ReplyAction="http://tempuri.org/ISistemaSrv/ImpresionTicketResponse")]
        System.Threading.Tasks.Task<CBX_Web_PetShopWeb.wsSistema.ImpresionTicketResponse> ImpresionTicketAsync(CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaSrv/ConsultarTSConfi_xCod", ReplyAction="http://tempuri.org/ISistemaSrv/ConsultarTSConfi_xCodResponse")]
        CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodResponse ConsultarTSConfi_xCod(CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaSrv/ConsultarTSConfi_xCod", ReplyAction="http://tempuri.org/ISistemaSrv/ConsultarTSConfi_xCodResponse")]
        System.Threading.Tasks.Task<CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodResponse> ConsultarTSConfi_xCodAsync(CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImpresionTicket", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImpresionTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CBX_Web_PetShopWeb.wsSistema.Session_Movi objSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public CBX_Web_PetShopWeb.wsSistema.Consumo[] listaConsumoSelects;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strMsjUsuario;
        
        public ImpresionTicketRequest() {
        }
        
        public ImpresionTicketRequest(CBX_Web_PetShopWeb.wsSistema.Session_Movi objSession, int intId, int tipo, CBX_Web_PetShopWeb.wsSistema.Consumo[] listaConsumoSelects, string strMsjUsuario) {
            this.objSession = objSession;
            this.intId = intId;
            this.tipo = tipo;
            this.listaConsumoSelects = listaConsumoSelects;
            this.strMsjUsuario = strMsjUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImpresionTicketResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImpresionTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ImpresionTicketResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strMsjUsuario;
        
        public ImpresionTicketResponse() {
        }
        
        public ImpresionTicketResponse(bool ImpresionTicketResult, string strMsjUsuario) {
            this.ImpresionTicketResult = ImpresionTicketResult;
            this.strMsjUsuario = strMsjUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarTSConfi_xCod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarTSConfi_xCodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long intIdSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intIdMenu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intIdSoft;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCoConfi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strMsjUsuario;
        
        public ConsultarTSConfi_xCodRequest() {
        }
        
        public ConsultarTSConfi_xCodRequest(long intIdSesion, int intIdMenu, int intIdSoft, string strCoConfi, string strMsjUsuario) {
            this.intIdSesion = intIdSesion;
            this.intIdMenu = intIdMenu;
            this.intIdSoft = intIdSoft;
            this.strCoConfi = strCoConfi;
            this.strMsjUsuario = strMsjUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarTSConfi_xCodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarTSConfi_xCodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CBX_Web_PetShopWeb.wsSistema.TSConfi ConsultarTSConfi_xCodResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strMsjUsuario;
        
        public ConsultarTSConfi_xCodResponse() {
        }
        
        public ConsultarTSConfi_xCodResponse(CBX_Web_PetShopWeb.wsSistema.TSConfi ConsultarTSConfi_xCodResult, string strMsjUsuario) {
            this.ConsultarTSConfi_xCodResult = ConsultarTSConfi_xCodResult;
            this.strMsjUsuario = strMsjUsuario;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaSrvChannel : CBX_Web_PetShopWeb.wsSistema.ISistemaSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaSrvClient : System.ServiceModel.ClientBase<CBX_Web_PetShopWeb.wsSistema.ISistemaSrv>, CBX_Web_PetShopWeb.wsSistema.ISistemaSrv {
        
        public SistemaSrvClient() {
        }
        
        public SistemaSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CBX_Web_PetShopWeb.wsSistema.ImpresionTicketResponse CBX_Web_PetShopWeb.wsSistema.ISistemaSrv.ImpresionTicket(CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest request) {
            return base.Channel.ImpresionTicket(request);
        }
        
        public bool ImpresionTicket(CBX_Web_PetShopWeb.wsSistema.Session_Movi objSession, int intId, int tipo, CBX_Web_PetShopWeb.wsSistema.Consumo[] listaConsumoSelects, ref string strMsjUsuario) {
            CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest inValue = new CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest();
            inValue.objSession = objSession;
            inValue.intId = intId;
            inValue.tipo = tipo;
            inValue.listaConsumoSelects = listaConsumoSelects;
            inValue.strMsjUsuario = strMsjUsuario;
            CBX_Web_PetShopWeb.wsSistema.ImpresionTicketResponse retVal = ((CBX_Web_PetShopWeb.wsSistema.ISistemaSrv)(this)).ImpresionTicket(inValue);
            strMsjUsuario = retVal.strMsjUsuario;
            return retVal.ImpresionTicketResult;
        }
        
        public System.Threading.Tasks.Task<CBX_Web_PetShopWeb.wsSistema.ImpresionTicketResponse> ImpresionTicketAsync(CBX_Web_PetShopWeb.wsSistema.ImpresionTicketRequest request) {
            return base.Channel.ImpresionTicketAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodResponse CBX_Web_PetShopWeb.wsSistema.ISistemaSrv.ConsultarTSConfi_xCod(CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest request) {
            return base.Channel.ConsultarTSConfi_xCod(request);
        }
        
        public CBX_Web_PetShopWeb.wsSistema.TSConfi ConsultarTSConfi_xCod(long intIdSesion, int intIdMenu, int intIdSoft, string strCoConfi, ref string strMsjUsuario) {
            CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest inValue = new CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest();
            inValue.intIdSesion = intIdSesion;
            inValue.intIdMenu = intIdMenu;
            inValue.intIdSoft = intIdSoft;
            inValue.strCoConfi = strCoConfi;
            inValue.strMsjUsuario = strMsjUsuario;
            CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodResponse retVal = ((CBX_Web_PetShopWeb.wsSistema.ISistemaSrv)(this)).ConsultarTSConfi_xCod(inValue);
            strMsjUsuario = retVal.strMsjUsuario;
            return retVal.ConsultarTSConfi_xCodResult;
        }
        
        public System.Threading.Tasks.Task<CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodResponse> ConsultarTSConfi_xCodAsync(CBX_Web_PetShopWeb.wsSistema.ConsultarTSConfi_xCodRequest request) {
            return base.Channel.ConsultarTSConfi_xCodAsync(request);
        }
    }
}
